---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprocessingservice
spec:
  selector:
    matchLabels:
      run: dataprocessingservice
  replicas: 1
  template:
    metadata:
      labels:
        run: dataprocessingservice
    spec:
      containers:
      - name: dataprocessingservice
        image: docker.io/adamquan/dataprocessingservice
        ports:
        - containerPort: 3000
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "https://tempo-us-central1.grafana.net:443"
        - name: OTEL_SERVICE_NAME
          value: "dataprocessingservice"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
          value: "Authorization=Bearer 160639:eyJrIjoiYjkzMDA1NDE0ODRhYWRjYzgwNjg0YTJlNzcyZmY0MThmMDNiOTRjMiIsIm4iOiJ0ZXN0IiwiaWQiOjYwMTM4MH0="

---
apiVersion: v1
kind: Service
metadata:
  name: dataprocessingservice
  labels:
    run: dataprocessingservice
  annotations:
    a8r.io/description: "Data processing adapter"
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: dataprocessingservice


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verylargejavaservice
spec:
  selector:
    matchLabels:
      run: verylargejavaservice
  replicas: 1
  template:
    metadata:
      labels:
        run: verylargejavaservice
    spec:
      containers:
      - name: verylargejavaservice
        image: docker.io/adamquan/verylargejavaservice
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "https://tempo-us-central1.grafana.net:443"
        - name: OTEL_SERVICE_NAME
          value: "verylargejavaservice"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
          value: "Authorization=Bearer 160639:eyJrIjoiYjkzMDA1NDE0ODRhYWRjYzgwNjg0YTJlNzcyZmY0MThmMDNiOTRjMiIsIm4iOiJ0ZXN0IiwiaWQiOjYwMTM4MH0="

---
apiVersion: v1
kind: Service
metadata:
  name: verylargejavaservice
  labels:
    run: verylargejavaservice
  annotations:
    a8r.io/description: "Web content-generating frontend app"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: verylargejavaservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verylargedatastore
spec:
  selector:
    matchLabels:
      run: verylargedatastore
  replicas: 1
  template:
    metadata:
      labels:
        run: verylargedatastore
    spec:
      containers:
      - name: verylargejavaservice
        image: docker.io/adamquan/verylargedatastore
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/opt/app/opentelemetry-javaagent.jar"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "https://tempo-us-central1.grafana.net:443"
        - name: OTEL_SERVICE_NAME
          value: "verylargedatastore"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
          value: "Authorization=Bearer 160639:eyJrIjoiYjkzMDA1NDE0ODRhYWRjYzgwNjg0YTJlNzcyZmY0MThmMDNiOTRjMiIsIm4iOiJ0ZXN0IiwiaWQiOjYwMTM4MH0="

---
apiVersion: v1
kind: Service
metadata:
  name: verylargedatastore
  labels:
    run: verylargedatastore
  annotations:
    a8r.io/description: "System of record for all Edgey Corp data"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: verylargedatastore
